import React, { useState } from 'react';
import Head from 'next/head';
// import Image from 'next/image'
import styles from '../styles/Home.module.css';

export default function Home() {
  const [count, setCount] = useState(0);
  return (
    <div>
      <Head>
        <title>Stat Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/energy-logo.png" />
      </Head>
      <h1 className='text-3xl text-center'>STAT TRACKER</h1>
      <div className='mt-5 text-center'>
        <h2 className='text-2xl'>Homeruns</h2>
        <div className='flex justify-center'>
          <button onClick={() => setCount(count - 1)} className='text-2xl mx-8 bg-blue-500 hover:bg-blue-700 text-white font-bold py-0.5 px-2 rounded-full'>-</button>
          <p className='text-2xl mt-1.5'>{count}</p>
          <button onClick={() => setCount(count + 1)} className='text-2xl mx-8 bg-blue-500 hover:bg-blue-700 text-white font-bold py-0.5 px-2 rounded-full'>+</button>
        </div>
      </div>
    </div>
  )
}
