import Head from 'next/head';
import Jumbotron from '../components/Jumbotron';
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stat Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/energy-logo.png" />
      </Head>

      {/* Image spanning entire screen/jumbotron maybe? */}
      <jumbotron>Houston Energy Image</jumbotron>
      <Jumbotron />


      {/* Navbar */}
      <nav>Navbar with links </nav>
    </div>
  )
}
